/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Astronauts } from "./astronauts.js";
import { Missions } from "./missions.js";
import { Webhooks } from "./webhooks.js";

export class SpaceExplorer extends ClientSDK {
  private _missions?: Missions;
  get missions(): Missions {
    return (this._missions ??= new Missions(this._options));
  }

  private _astronauts?: Astronauts;
  get astronauts(): Astronauts {
    return (this._astronauts ??= new Astronauts(this._options));
  }

  private _webhooks?: Webhooks;
  get webhooks(): Webhooks {
    return (this._webhooks ??= new Webhooks(this._options));
  }
}
