/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksRegisterMissionUpdates } from "../funcs/webhooksRegisterMissionUpdates.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Webhooks extends ClientSDK {
  /**
   * Register for mission updates
   */
  async registerMissionUpdates(
    request: components.WebhookRegistration,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(webhooksRegisterMissionUpdates(
      this,
      request,
      options,
    ));
  }
}
