/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteMissionRequest = {
  /**
   * ID of the mission
   */
  missionId: string;
};

/** @internal */
export const DeleteMissionRequest$inboundSchema: z.ZodType<
  DeleteMissionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  missionId: z.string(),
});

/** @internal */
export type DeleteMissionRequest$Outbound = {
  missionId: string;
};

/** @internal */
export const DeleteMissionRequest$outboundSchema: z.ZodType<
  DeleteMissionRequest$Outbound,
  z.ZodTypeDef,
  DeleteMissionRequest
> = z.object({
  missionId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteMissionRequest$ {
  /** @deprecated use `DeleteMissionRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteMissionRequest$inboundSchema;
  /** @deprecated use `DeleteMissionRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteMissionRequest$outboundSchema;
  /** @deprecated use `DeleteMissionRequest$Outbound` instead. */
  export type Outbound = DeleteMissionRequest$Outbound;
}
